### PR TITLE
Improve Django 1.11 compatibility. Import `flatatt` from the correct place.

### PR DESCRIPTION
**Pull request by dpaskov**
This is compatible with Django 1.8, 1.9, 1.10 & 1.11.

### CODE REVIEW

**Comment by dpaskov** [comment]
Will you release this with 0.5.6?
Thank you in advance.

**Comment by barseghyanartur** [comment]
@dpaskov:

Sure. Thanks for your support.

**Comment by dpaskov** [comment]
@barseghyanartur 
Could you release latest version?

**Comment by barseghyanartur** [comment]
@dpaskov:

Yep. Tonight.

**Comment by dpaskov** [comment]
@barseghyanartur 
Actually I hit a couple more deprecation things with Django 1.11 and will prepare a PR for them, so all could go inside new release.

**Comment by dpaskov** [comment]
Only this is needed: https://github.com/barseghyanartur/django-dash/pull/30

**Comment by barseghyanartur** [comment]
@dpaskov:

Done.

**Comment by dpaskov** [comment]
Thank you!

**Pull request merged**
